-- =====================================================================
-- HONDA SERVICE TICKETING & SLA SYSTEM - COMPLETE SUPABASE POSTGRESQL SCHEMA
-- Matches exact production schema of SQLite (data/tickets.db)
-- =====================================================================

-- Clean up existing tables to ensure clean recreation
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS user_stage_permissions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sla_alerts CASCADE;
DROP TABLE IF EXISTS stage_logs CASCADE;
DROP TABLE IF EXISTS ticket_parts CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS surveyor_insurance_map CASCADE;
DROP TABLE IF EXISTS surveyors CASCADE;
DROP TABLE IF EXISTS insurance_companies CASCADE;
DROP TABLE IF EXISTS parts CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS customer_phones CASCADE;
DROP TABLE IF EXISTS customer_branches CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS outlets CASCADE;

-- 1. Outlets / Branches
CREATE TABLE outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  location TEXT,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Customers
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  primary_phone TEXT NOT NULL,
  branch_id BIGINT REFERENCES outlets(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. Customer Alternate Phones
CREATE TABLE customer_phones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  phone TEXT NOT NULL
);

-- 4. Customer Branches (Multi-branch mapping)
CREATE TABLE customer_branches (
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  outlet_id BIGINT NOT NULL REFERENCES outlets(id) ON DELETE CASCADE,
  PRIMARY KEY (customer_id, outlet_id)
);

-- 5. Vehicles
CREATE TABLE vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  vehicle_no TEXT UNIQUE,
  vehicle_name TEXT NOT NULL,
  model TEXT,
  color TEXT,
  chassis_no TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. Parts Catalog
CREATE TABLE parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_code TEXT,
  part_name TEXT NOT NULL UNIQUE,
  default_cost NUMERIC DEFAULT 0,
  stock_qty INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 7. Insurance Companies
CREATE TABLE insurance_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  contact_info TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8. Surveyors
CREATE TABLE surveyors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. Surveyor - Insurance Mapping
CREATE TABLE surveyor_insurance_map (
  surveyor_id BIGINT NOT NULL REFERENCES surveyors(id) ON DELETE CASCADE,
  insurance_company_id BIGINT NOT NULL REFERENCES insurance_companies(id) ON DELETE CASCADE,
  PRIMARY KEY (surveyor_id, insurance_company_id)
);

-- 10. Tickets (Complete with all stage and operational date columns)
CREATE TABLE tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_number TEXT UNIQUE NOT NULL,
  outlet_id BIGINT NOT NULL REFERENCES outlets(id),
  outlet_name TEXT NOT NULL,
  customer_id BIGINT REFERENCES customers(id),
  vehicle_id BIGINT REFERENCES vehicles(id),
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  vehicle_no TEXT,
  vehicle_name TEXT NOT NULL,
  model TEXT,
  color TEXT,
  chassis_number TEXT NOT NULL,
  current_stage_id INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'OPEN',
  parts_order_required INTEGER DEFAULT 0,
  resurvey_required INTEGER DEFAULT 0,
  is_bypassed INTEGER DEFAULT 0,
  bypass_stage_id INTEGER,
  bypass_reason TEXT,
  bypassed_at TIMESTAMPTZ,
  arrival_date TIMESTAMPTZ NOT NULL,
  estimate_date TIMESTAMPTZ,
  damaged_parts TEXT,
  estimated_cost NUMERIC DEFAULT 0,
  insurance_intimation_date TIMESTAMPTZ,
  insurance_company TEXT,
  survey_date TIMESTAMPTZ,
  surveyor_name TEXT,
  surveyor_phone TEXT,
  approval_date TIMESTAMPTZ,
  parts_order_date TIMESTAMPTZ,
  parts_arrival_date TIMESTAMPTZ,
  work_start_date TIMESTAMPTZ,
  work_complete_date TIMESTAMPTZ,
  invoice_date TIMESTAMPTZ,
  resurvey_date TIMESTAMPTZ,
  delivery_date TIMESTAMPTZ,
  closure_date TIMESTAMPTZ,
  current_stage_entered_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  parts_status_note TEXT,
  waiting_delivery_date TIMESTAMPTZ,
  customer_approval_exempt INTEGER DEFAULT 0
);

-- 11. Ticket Stage Logs (stage_logs)
CREATE TABLE stage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  stage_name TEXT NOT NULL,
  entered_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  sla_limit_wd INTEGER,
  elapsed_wd INTEGER DEFAULT 0,
  sla_status TEXT NOT NULL DEFAULT 'WITHIN_SLA',
  data_json TEXT
);

-- 12. Ticket Parts
CREATE TABLE ticket_parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  part_name TEXT NOT NULL,
  part_code TEXT,
  quantity INTEGER DEFAULT 1,
  unit_cost NUMERIC DEFAULT 0,
  total_cost NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  part_status TEXT DEFAULT 'ORDERED',
  notes TEXT,
  arrived_at TIMESTAMPTZ,
  insurance_approved INTEGER DEFAULT 0,
  company_approved INTEGER DEFAULT 0,
  customer_approval_status TEXT DEFAULT 'PENDING',
  is_critical_to_start INTEGER DEFAULT 0
);

-- 13. SLA Alerts
CREATE TABLE sla_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  outlet_id BIGINT NOT NULL REFERENCES outlets(id),
  stage_id INTEGER NOT NULL,
  breached_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  days_overdue INTEGER DEFAULT 0,
  status TEXT DEFAULT 'ACTIVE'
);

-- 14. Users (Authentication)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 15. User Sessions (token is primary key)
CREATE TABLE user_sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 16. User Stage Permissions
CREATE TABLE user_stage_permissions (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  can_read INTEGER NOT NULL DEFAULT 1,
  can_write INTEGER NOT NULL DEFAULT 1,
  can_delete INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(user_id, stage_id)
);

-- 17. Ticket Comments & Threaded Notes
CREATE TABLE ticket_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES ticket_comments(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  user_role TEXT,
  content TEXT NOT NULL,
  mentions TEXT[],
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 18. User Notifications (Mentions, Replies, Activity)
CREATE TABLE user_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  actor_name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'MENTION', 'REPLY', 'NOTE_ADDED'
  ticket_id BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  ticket_number TEXT,
  comment_id BIGINT REFERENCES ticket_comments(id) ON DELETE CASCADE,
  content_snippet TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================================
-- PERFORMANCE INDEXES
-- =====================================================================
CREATE INDEX idx_tickets_stage ON tickets(current_stage_id);
CREATE INDEX idx_tickets_outlet ON tickets(outlet_id);
CREATE INDEX idx_tickets_status ON tickets(status);
CREATE INDEX idx_tickets_customer ON tickets(customer_id);
CREATE INDEX idx_tickets_vehicle ON tickets(vehicle_id);
CREATE INDEX idx_stage_logs_ticket ON stage_logs(ticket_id);
CREATE INDEX idx_ticket_parts_ticket ON ticket_parts(ticket_id);
CREATE INDEX idx_user_sessions_user ON user_sessions(user_id);
CREATE INDEX idx_user_permissions_user ON user_stage_permissions(user_id);
CREATE INDEX idx_ticket_comments_ticket ON ticket_comments(ticket_id);
CREATE INDEX idx_ticket_comments_parent ON ticket_comments(parent_id);
CREATE INDEX idx_user_notifications_user ON user_notifications(user_id);
CREATE INDEX idx_user_notifications_unread ON user_notifications(user_id, is_read);

-- =====================================================================
-- ROW LEVEL SECURITY (RLS) - Permissive for backend service role
-- =====================================================================
ALTER TABLE outlets ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_phones ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE insurance_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE surveyors ENABLE ROW LEVEL SECURITY;
ALTER TABLE surveyor_insurance_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE stage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE sla_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_stage_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Full access on outlets" ON outlets FOR ALL USING (true);
CREATE POLICY "Full access on customers" ON customers FOR ALL USING (true);
CREATE POLICY "Full access on customer_phones" ON customer_phones FOR ALL USING (true);
CREATE POLICY "Full access on customer_branches" ON customer_branches FOR ALL USING (true);
CREATE POLICY "Full access on vehicles" ON vehicles FOR ALL USING (true);
CREATE POLICY "Full access on parts" ON parts FOR ALL USING (true);
CREATE POLICY "Full access on insurance_companies" ON insurance_companies FOR ALL USING (true);
CREATE POLICY "Full access on surveyors" ON surveyors FOR ALL USING (true);
CREATE POLICY "Full access on surveyor_insurance_map" ON surveyor_insurance_map FOR ALL USING (true);
CREATE POLICY "Full access on tickets" ON tickets FOR ALL USING (true);
CREATE POLICY "Full access on stage_logs" ON stage_logs FOR ALL USING (true);
CREATE POLICY "Full access on ticket_parts" ON ticket_parts FOR ALL USING (true);
CREATE POLICY "Full access on sla_alerts" ON sla_alerts FOR ALL USING (true);
CREATE POLICY "Full access on users" ON users FOR ALL USING (true);
CREATE POLICY "Full access on user_sessions" ON user_sessions FOR ALL USING (true);
CREATE POLICY "Full access on user_stage_permissions" ON user_stage_permissions FOR ALL USING (true);

-- =====================================================================
-- RPC FUNCTIONS: DYNAMIC QUERY RUNNERS
-- =====================================================================
CREATE OR REPLACE FUNCTION exec_sql(sql_query text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result json;
BEGIN
  EXECUTE 'SELECT json_agg(t) FROM (' || sql_query || ') t' INTO result;
  RETURN coalesce(result, '[]'::json);
END;
$$;

CREATE OR REPLACE FUNCTION exec_mutation(sql_query text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE sql_query;
  RETURN json_build_object('success', true);
END;
$$;
